DO
$$
BEGIN
    DROP TABLE IF EXISTS visualitzacio_capitol CASCADE;
    DROP TABLE IF EXISTS visualitzacio_pelicula CASCADE;
    DROP TABLE IF EXISTS relacionat CASCADE;
    DROP TABLE IF EXISTS capitol CASCADE;
    DROP TABLE IF EXISTS temporada CASCADE;
    DROP TABLE IF EXISTS serie CASCADE;
    DROP TABLE IF EXISTS pelicula CASCADE;
    DROP TABLE IF EXISTS contingut CASCADE;
    DROP TABLE IF EXISTS usuari CASCADE;
    DROP TABLE IF EXISTS qualificacio_edat CASCADE;
    DROP TABLE IF EXISTS modalitat_subscripcio CASCADE;
END;
$$;
